package record

import ()

type Submitter interface {
	Submit(r *Request) (*Result, error)
}

type Request struct {
	Ref_ID int
}

type Record struct {
	OBJECTID             string `json:"OBJECTID,omitempty"`
	FEATUREID            string `json:"FEATUREID,omitempty"`
	PARCELPIN            string `json:"PARCELPIN,omitempty"`
	STREETID             string `json:"STREETID,omitempty"`
	PREADDRNUM           string `json:"PREADDRNUM,omitempty"`
	STNUMBER             string `json:"STNUMBER,omitempty"`
	PREMOD               string `json:"PREMOD,omitempty"`
	PREDIR               string `json:"PREDIR,omitempty"`
	POSTMOD              string `json:"POSTMOD,omitempty"`
	PRETYPE              string `json:"PRETYPE,omitempty"`
	POSTDIR              string `json:"POSTDIR,omitempty"`
	LABEL                string `json:"LABEL,omitempty"`
	UNITLOW              string `json:"UNITLOW,omitempty"`
	UNITHIGH             string `json:"UNITHIGH,omitempty"`
	UNITACTUAL           string `json:"UNITACTUAL,omitempty"`
	CITY                 string `json:"CITY,omitempty"`
	ZIP                  string `json:"ZIP,omitempty"`
	ZIP4                 string `json:"ZIP4,omitempty"`
	PTTYPE               string `json:"PTTYPE,omitempty"`
	PTTYPESUB            string `json:"PTTYPESUB,omitempty"`
	SUBDIVISION          string `json:"SUBDIVISION,omitempty"`
	STATUS               string `json:"STATUS,omitempty"`
	COMMONNAME           string `json:"COMMONNAME,omitempty"`
	SOURCE               string `json:"SOURCE,omitempty"`
	COMMENT              string `json:"COMMENT_,omitempty"`
	CREATEDATE           string `json:"CREATEDATE,omitempty"`
	STRNUMBERHI          string `json:"STRNUMBERHI,omitempty"`
	W_METER_NUM          string `json:"W_METER_NUM,omitempty"`
	W_PREMISE_ID         string `json:"W_PREMISE_ID,omitempty"`
	W_METER_TYPE         string `json:"W_METER_TYPE,omitempty"`
	W_METER_IN_CITY      string `json:"W_METER_IN_CITY,omitempty"`
	W_GT_NAME            string `json:"W_GT_NAME,omitempty"`
	W_GT_CITY_INSP       string `json:"W_GT_CITY_INSP,omitempty"`
	W_SP_TANK_ADDR       string `json:"W_SP_TANK_ADDR,omitempty"`
	W_SP_TO_CITYSEWER    string `json:"W_SP_TO_CITYSEWER,omitempty"`
	W_SP_AVAIL_TO_CONN   string `json:"W_SP_AVAIL_TO_CONN,omitempty"`
	W_MH_IN_CITY         string `json:"W_MH_IN_CITY,omitempty"`
	W_SWB_IN_CITY        string `json:"W_SWB_IN_CITY,omitempty"`
	W_HYDRANT_IN_CITY    string `json:"W_HYDRANT_IN_CITY,omitempty"`
	BLDG_ZONE            string `json:"BLDG_ZONE,omitempty"`
	BLDGINSPDISPLINE     string `json:"BLDG_INSP_DISPLINE,omitempty"`
	BLDGDCA              string `json:"BLDG_DCA,omitempty"`
	BLDGINSPRNAME        string `json:"BLDG_INSPR_NAME,omitempty"`
	ELEMSCHZONE          string `json:"ELEM_SCH_ZONE,omitempty"`
	HIGHSCHZONE          string `json:"HIGH_SCH_ZONE,omitempty"`
	MIDSCHZONE           string `json:"MID_SCH_ZONE,omitempty"`
	LANDLOTNUM           string `json:"LAND_LOT_NUM,omitempty"`
	TAXPIN               string `json:"TAXPIN,omitempty"`
	PRSANAME             string `json:"PRSA_NAME,omitempty"`
	NPU_NAME             string `json:"NPU_NAME,omitempty"`
	CDBGNAME             string `json:"CDBGNAME,omitempty"`
	DISTZONING           string `json:"DIST_ZONING,omitempty"`
	OLDISTZONING         string `json:"OL_DIST_ZONING,omitempty"`
	ADDRESSINCITY        string `json:"ADDRESS_IN_CITY,omitempty"`
	COUNCIL_DIST         string `json:"COUNCIL_DIST,omitempty"`
	COUNCIL_MEMBER       string `json:"COUNCIL_MEMBER,omitempty"`
	VOTEPRCTS            string `json:"VOTE_PRCTS,omitempty"`
	POLICEZONE           string `json:"POLICE_ZONE,omitempty"`
	POLICESTCOUNTY       string `json:"POLICE_ST_COUNTY,omitempty"`
	FIRESTNAME           string `json:"FIRE_ST_NAME,omitempty"`
	FIRESTADDR           string `json:"FIRE_ST_ADDR,omitempty"`
	FIRESTTERR           string `json:"FIRE_ST_TERR,omitempty"`
	FIREBATTALION        string `json:"FIRE_BATTALION,omitempty"`
	PARKNAME             string `json:"PARK_NAME,omitempty"`
	PARKADDR             string `json:"PARK_ADDR,omitempty"`
	FULLSTREETADDRESS    string `json:"FULL_STREET_ADDRESS,omitempty"`
	STREETNUMBER         string `json:"STREET_NUMBER,omitempty"`
	STREETPREFIX         string `json:"STREET_PREFIX,omitempty"`
	STREETNAME           string `json:"STREET_NAME,omitempty"`
	STREETTYPE           string `json:"STREET_TYPE,omitempty"`
	STREETSUFFIX         string `json:"STREET_SUFFIX,omitempty"`
	UNITNUMBER           string `json:"UNIT_NUMBER,omitempty"`
	STATE                string `json:"STATE,omitempty"`
	ZIPCODE              string `json:"ZIPCODE,omitempty"`
	LATITUDE             string `json:"LATITUDE,omitempty"`
	LONGITUDE            string `json:"LONGITUDE,omitempty"`
	E311UNIQUEID         string `json:"E311_UNIQUE_ID,omitempty"`
	TAXPINORIGINAL       string `json:"TAXPIN_ORIGINAL,omitempty"`
	NEARPARKDISTANCE     string `json:"NEAR_PARK_DISTANCE,omitempty"`
	NEARPOLICESTFID      string `json:"NEAR_POLICE_ST_FID,omitempty"`
	NEARPOLICESTNUMBER   string `json:"NEAR_POLICE_ST_NUMBER,omitempty"`
	NEARPOLICESTADDR     string `json:"NEAR_POLICE_ST_ADDR,omitempty"`
	NEARHYDRANTID        string `json:"NEAR_HYDRANT_ID,omitempty"`
	NEARHYDRANTDISTANCE  string `json:"NEAR_HYDRANT_DISTANCE,omitempty"`
	NEARGTDIST           string `json:"NEAR_GT_DIST,omitempty"`
	SERVSTAT             string `json:"SERV_STAT,omitempty"`
	FINALMATCH           string `json:"FINAL_MATCH,omitempty"`
	E311SOURCE           string `json:"E311_SOURCE,omitempty"`
	E311STATUS           string `json:"E311_STATUS,omitempty"`
	NEARDIST             string `json:"NEAR_DIST,omitempty"`
	WCUSTOMERNUMBER      string `json:"W_CUSTOMERNUMBER,omitempty"`
	REFPARCELUNIQUEID    string `json:"REF_PARCEL_UNIQUE_ID,omitempty"`
	REFWMUNIQUEID        string `json:"REF_WM_UNIQUE_ID,omitempty"`
	WSWBNAME             string `json:"W_SWB_NAME,omitempty"`
	NEARMHFID            string `json:"NEAR_MH_FID,omitempty"`
	POLICEBEAT           string `json:"POLICE_BEAT,omitempty"`
	PARCELTEST           string `json:"PARCEL_TEST,omitempty"`
	NEWPARELREFERENCEID  string `json:"NEW_PAREL_REFERENCE_ID,omitempty"`
	NEWPARCELREFERENCEID string `json:"NEW_PARCEL_REFERENCE_ID,omitempty"`
	E311FINALLABEL       string `json:"E311_FINAL_LABEL,omitempty"`
	NEWSTATUS            string `json:"NEW_STATUS,omitempty"`
	STATUS1              string `json:"STATUS_1,omitempty"`
	NEWSTATUS1           string `json:"NEW_STATUS_1,omitempty"`
	E311ADDRESSLABEL     string `json:"E311_ADDRESS_LABEL,omitempty"`
	RANK                 string `json:"RANK,omitempty"`
	SEPARATOR            string `json:"SEPARATOR,omitempty"`
	POSTTYPE             string `json:"POSTTYPE,omitempty"`
	E311GTSTATUS         string `json:"E311_GT_STATUS,omitempty"`
	E311GTADDRESSSTD     string `json:"E311_GT_ADDRESS_STD,omitempty"`
	NEARMHID             string `json:"NEAR_MH_ID,omitempty"`
	NEARMHDIST           string `json:"NEAR_MH_DIST,omitempty"`
	NEARPARKID           string `json:"NEAR_PARK_ID,omitempty"`
	NPU12                string `json:"NPU_12,omitempty"`
	REFE311UNIQUEID      string `json:"REF_E311_UNIQUEID,omitempty"`
	WHYDRANTDISTANCE     string `json:"W_HYDRANT_DISTANCE,omitempty"`
	SHAPE                string `json:"SHAPE,omitempty"`
	DAYGAR               string `json:"DAYGAR,omitempty"`
	DAYREC               string `json:"DAYREC,omitempty"`
	DAYYAR               string `json:"DAYYAR,omitempty"`
	LINK                 string `json:"LINK,omitempty"`
	OWNER                string `json:"OWNER,omitempty"`
	TAXDIST              string `json:"TAXDIST,omitempty"`
	OWNERADDR1           string `json:"OWNERADDR1,omitempty"`
	OWNERADDR2           string `json:"OWNERADDR2,omitempty"`
	TOTASSESS            string `json:"TOTASSESS,omitempty"`
	LANDASSESS           string `json:"LANDASSESS,omitempty"`
	IMPRASSESS           string `json:"IMPRASSESS,omitempty"`
	TOTAPPR              string `json:"TOTAPPR,omitempty"`
	LANDAPPR             string `json:"LANDAPPR,omitempty"`
	IMPRAPPR             string `json:"IMPRAPPR,omitempty"`
	LUCODE               string `json:"LUCODE,omitempty"`
	CLASSCODE            string `json:"CLASSCODE,omitempty"`
	LIVUNITS             string `json:"LIVUNITS,omitempty"`
	LANDACRES            string `json:"LANDACRES,omitempty"`
	NBRHOOD              string `json:"NBRHOOD,omitempty"`
	SUBDIV               string `json:"SUBDIV,omitempty"`
	SUBDIVNUM            string `json:"SUBDIVNUM,omitempty"`
	SUBDIVLOT            string `json:"SUBDIVLOT,omitempty"`
	SUBDIVBLCK           string `json:"SUBDIVBLCK,omitempty"`
	OWNERSTATE           string `json:"OWNERSTATE,omitempty"`
	OWNERZIP             string `json:"OWNERZIP,omitempty"`
	DAYBUL               string `json:"DAYBUL,omitempty"`
	DAYCUT               string `json:"DAYCUT,omitempty"`
	DAYSWE               string `json:"DAYSWE,omitempty"`
	OID                  string `json:"OID,omitempty"`
}

type Result []Record
