name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Configure git for private modules
      env:
        TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
      run: git config --global url."https://abrie:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: make dependencies

    - name: Build
      run: make build

    - name: Test
      run: make test
